### ISSUE TITLE
[Enhancement] Config to customize the chunk loader blocks

### ISSUE THREAD

**Issue by kaal-1** [Time6628/betterchunkloader-sponge#1]
In the bukkit version of this plugin there is a config in which you can specify the blocks that should act like chunk loaders. This is specially useful in servers where you want to make the craft of chunk loaders harder, since you can't really modify the craft of iron and diamond blocks without it affecting a lot of other things in the pack. Do you think it would be possible to add something like that?

**Comment by Time6628** [comment]
https://bitbucket.org/shadownode/betterchunkloader/src
